### ISSUE TITLE
fix xml while importing

### ISSUE THREAD

**Issue by berz** [philipmat/discogs-xml2db#89]
At the moment the fix-xml script has to be run before starting the import process. The only thing this script does is to remove some characters. I was wondering if this could be done while importing the file. 

The main advantage for me would be that I need less free disk space to run the program. The fix-xml stage is the step that takes up the most disk space as it copies the files while doing the substitutions. Since the latest releases file is 33GiB I need at least 66GiB of free space for this step, which is a lot on my cramped SSD.
Additionally this would simplify the importing process by removing one step.

**Comment by philipmat** [comment]
I hear you, but I'm not really sure how well the xml parser handles malformed documents. My guess is not well, but I'm willing to be proven wrong.

I'll close this issue because, albeit subpar, we do have a working solution. Should you wish to investigate and even provide a PR (yes please!) I'd be more than happy to accept it.
